### ISSUE TITLE
Bug: Cannot use it as common js

### ISSUE THREAD

**Issue by simonboisset** [aptabase/aptabase-js#1]
We can only use it as `esm` module ans it make my Remix app crash for that.
I can make a PR to fix it.

**Comment by goenning** [comment]
hey @simonboisset there's a React SDK now that works with Remix, would you like to give it a try? 
https://github.com/aptabase/aptabase-js/tree/main/packages/react

**Comment by simonboisset** [comment]
Hi ! Thanks for the work.
 I will try it and give you my feedback
