### ISSUE TITLE
Allow setting isDebug manually so it can work in certain environments

### ISSUE THREAD

**Issue by Jordan-Ellis** [aptabase/aptabase-js#4]
When using a framework like ionic capacitor, the app is hosted from localhost even in production. Because if this it's impossible to run the web analytics script without it always being in debug mode.

It would be great if there was a way to manually set debug mode when initializing Aptabase. Something along the lines of:

```js
init('A-EU-3872464800', {
    isDebug: false, // <- custom code to determine if in production
});
```

**Comment by goenning** [comment]
Yeah that sounds like a good idea. I wonder if there’s any other more reliable method of identifying if the app is in production mode.

I don’t know enough about ionic but we could release a @aptabase/ionic package for example, which could rely on ionic specific functions to get that, as well as getting OS name, OS version, etc

**Comment by Jordan-Ellis** [comment]
I'm not sure if ionic has a single way to check for production, since it can be run with different build tools or environments. In my specific case I'm using ionic with nuxt, so I'd have to use the nuxt process.ENV variable. Ionic does have its own cli as well, but I don't know much about it.

That would be really great to get the device information! It would probably make sense to create a capacitor plugin since ionic is UI only. Capacitor has a plugin to get device info here: https://capacitorjs.com/docs/apis/device#deviceinfo

**Comment by goenning** [comment]
@Jordan-Ellis Let's start with your initial suggestion. Have a look at version 0.3.0 of the JS SDK, there's a `isDebug` property as you suggested.

**Comment by Jordan-Ellis** [comment]
Awesome! Thanks!
