### ISSUE TITLE
Issue when importing `@aptabase/web` on server

### ISSUE THREAD

**Issue by ngregrichardson** [aptabase/aptabase-js#7]
Loving Aptabase so far, but running into an annoyance with using this SDK with SSR frameworks (specifically SvelteKit). I want to exclusively run events clientside, so I make sure to run `init` and `trackEvent` only on the client. However, functions like `getBrowserLocale` are called on import to create `defaultLocale` (https://github.com/aptabase/aptabase-js/blob/main/packages/shared.ts#L1), which causes an error since `navigator.languages` does not exist (`TypeError: Cannot read properties of undefined (reading 'length')`)

Would you accept a PR to either:
1. Make sure `navigator.languages` exists before checking length

*or*

2. `defaultLocale` is a "singleton" that is first created when it is requested (which seems to only be in `sendEvent()`

I'd be happy to do the work, just want to chat about how it should be done (if at all)

**Comment by ivnbogdan** [comment]
Thanks for using Aptabase and for reporting this!

This definitely needs a fix, and it probably makes more sense to read the locale value as late as possible - so like you mentioned in option 2, on sendEvent.
That way when sendEvent is called and is executed on client side navigator.languages should be available.

Adding an extra check with `navigator.languages?.length` also helps, but it doesn't result in the correct language being loaded, so would go with reading it on `sendEvent` primarily
